export const ikeaShops = [
  {
    country: "Slovakia",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/sk/sk/p/-",
  },
  {
    country: "Austria",
    currency: "EUR",
    img: ".image.lazyloaded",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/at/en/p/-",
  },
  {
    country: "Belgium",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/be/en/p/-",
  },
  {
    country: "Bulgaria",
    currency: "BGN",
    img: ".image.lazyloaded",
    name: "",
    desc: ".product-title",
    price: ".price",
    priceDecimal: "",
    url: "https://www.ikea.bg/products/",
  },
  {
    country: "Croatia",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/hr/hr/p/-",
  },
  {
    country: "Cyprus",
    currency: "EUR",
    img: ".image.lazyloaded",
    name: "",
    desc: ".product-title",
    price: ".price",
    priceDecimal: "",
    url: "https://www.ikea.com.cy/en/p/-",
  },
  {
    country: "Czech Republic",
    currency: "CZK",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/cz/en/p/-",
  },
  {
    country: "Denmark",
    currency: "DKK",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/dk/da/p/-",
  },
  {
    country: "Estonia",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: "data-price",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.ee/en/products/",
  },
  {
    country: "Finland",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/fi/fi/p/-",
  },
  {
    country: "France",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/fr/fr/p/-",
  },
  {
    country: "Germany",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/de/de/p/-",
  },
  {
    country: "Greece",
    currency: "EUR",
    img: ".image.lazyloaded",
    name: "",
    desc: ".product-title",
    price: ".price",
    priceDecimal: "",
    url: "https://www.ikea.gr/en/p/-",
  },
  {
    country: "Hungary",
    currency: "HUF",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/hu/hu/p/-",
  },
  {
    country: "Iceland",
    currency: "ISK",
    img: ".pip-image",
    name: ".display-6.mr-2.mb-0",
    desc: ".itemFacts",
    price: ".price__integer",
    priceDecimal: "",
    url: "https://www.ikea.is/is/p/-",
  },
  {
    country: "Ireland",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/ie/en/p/-",
  },
  {
    country: "Italy",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/it/it/p/-",
  },
  {
    country: "Latvia",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: "data-price",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.lv/en/products/",
  },
  {
    country: "Lithuania",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: "data-price",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.lt/en/products/",
  },
  {
    country: "Netherlands",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/nl/en/p/-",
  },
  {
    country: "Norway",
    currency: "NOK",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/no/no/p/-",
  },
  {
    country: "Poland",
    currency: "PLN",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/pl/pl/p/-",
  },
  {
    country: "Portugal",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/pt/en/p/-",
  },
  {
    country: "Romania",
    currency: "RON",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/ro/ro/p/-",
  },
  {
    country: "Slovenia",
    currency: "EUR",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/si/sl/p/-",
  },
  {
    country: "Serbia",
    currency: "RSD",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/rs/sr/p/-",
  },
  // {
  //   country: "Spain",
  //   currency: "EUR",
  //   img: ".pip-image",
  //   name: ".pip-header-section__title--big.notranslate",
  //   desc: ".pip-header-section__description-text",
  //   price: ".pip-temp-price__integer",
  //   priceDecimal: ".pip-temp-price__decimal",
  //   url: "https://www.ikea.es/",
  // },
  {
    country: "Sweden",
    currency: "SEK",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/se/sv/p/-",
  },
  {
    country: "Switzerland",
    currency: "CHF",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/ch/en/p/-",
  },
  {
    country: "United Kingdom",
    currency: "GBP",
    img: ".pip-image",
    name: ".pip-header-section__title--big.notranslate",
    desc: ".pip-header-section__description-text",
    price: ".pip-temp-price__integer",
    priceDecimal: ".pip-temp-price__decimal",
    url: "https://www.ikea.com/gb/en/p/-",
  },
];
